MAP_NAME = GetMapName()
if MAP_NAME == "skillshot_wars" then

CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_GOODGUYS] = 5
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_BADGUYS]  = 5
KILLS_TO_END_GAME_FOR_TEAM = 50

elseif MAP_NAME == "skillshot_3v3" then

CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_GOODGUYS] = 3
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_BADGUYS]  = 3
KILLS_TO_END_GAME_FOR_TEAM = 30

end
